"""empty message

Revision ID: 13109e7d6164
Revises: ab5678099b0
Create Date: 2014-10-30 18:02:46.389000

"""

# revision identifiers, used by Alembic.
revision = '13109e7d6164'
down_revision = 'ab5678099b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_result',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('match_pk', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('team_pk', sa.Integer(), nullable=True),
    sa.Column('player_pk', sa.Integer(), nullable=True),
    sa.Column('status_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_pk'], ['match.pk'], ),
    sa.ForeignKeyConstraint(['player_pk'], ['player.pk'], ),
    sa.ForeignKeyConstraint(['status_pk'], ['status.pk'], ),
    sa.ForeignKeyConstraint(['team_pk'], ['team.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_result')
    ### end Alembic commands ###
