"""empty message

Revision ID: 161949ae2b53
Revises: 18ba32b0e6b7
Create Date: 2014-11-22 15:55:25.345000

"""

# revision identifiers, used by Alembic.
revision = '161949ae2b53'
down_revision = '18ba32b0e6b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('accumulate_limit_of_participation', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('assist', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('match_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'match_count')
    op.drop_column('player', 'assist')
    op.drop_column('player', 'accumulate_limit_of_participation')
    ### end Alembic commands ###
