"""empty message

Revision ID: 16e6bbfff5ba
Revises: 573e77e8d304
Create Date: 2014-11-15 17:14:24.461000

"""

# revision identifiers, used by Alembic.
revision = '16e6bbfff5ba'
down_revision = '573e77e8d304'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('auth_key', sa.String(length=20), nullable=True))
    op.add_column('player', sa.Column('authorized', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'authorized')
    op.drop_column('player', 'auth_key')
    ### end Alembic commands ###
