"""empty message

Revision ID: 17cc1910049c
Revises: 3d0b16424ac2
Create Date: 2014-11-10 15:28:50.766000

"""

# revision identifiers, used by Alembic.
revision = '17cc1910049c'
down_revision = '3d0b16424ac2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
