"""empty message

Revision ID: 1fa7d3248053
Revises: 59747d029dbf
Create Date: 2014-11-10 15:34:17.222000

"""

# revision identifiers, used by Alembic.
revision = '1fa7d3248053'
down_revision = '59747d029dbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('limit_count', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('limit_of_participation', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('red_card_count', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('yellow_card_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'yellow_card_count')
    op.drop_column('player', 'red_card_count')
    op.drop_column('player', 'limit_of_participation')
    op.drop_column('player', 'limit_count')
    ### end Alembic commands ###
