"""empty message

Revision ID: 252a23273e32
Revises: None
Create Date: 2014-10-22 16:14:10.153000

"""

# revision identifiers, used by Alembic.
revision = '252a23273e32'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
