"""empty message

Revision ID: 28ee22c17aae
Revises: 4ee37c58c652
Create Date: 2014-11-17 21:08:59.282000

"""

# revision identifiers, used by Alembic.
revision = '28ee22c17aae'
down_revision = '4ee37c58c652'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
