"""empty message

Revision ID: 2d3b2fdff269
Revises: 16e6bbfff5ba
Create Date: 2014-11-15 18:01:56.513000

"""

# revision identifiers, used by Alembic.
revision = '2d3b2fdff269'
down_revision = '16e6bbfff5ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
