"""empty message

Revision ID: 3d0b16424ac2
Revises: 4fe73b1cc4df
Create Date: 2014-11-10 15:01:33.965000

"""

# revision identifiers, used by Alembic.
revision = '3d0b16424ac2'
down_revision = '4fe73b1cc4df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
