"""empty message

Revision ID: 45a1e07f043a
Revises: fd1991cc204
Create Date: 2014-11-06 14:24:25.304000

"""

# revision identifiers, used by Alembic.
revision = '45a1e07f043a'
down_revision = 'fd1991cc204'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('yellow_card', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'yellow_card')
    ### end Alembic commands ###
