"""empty message

Revision ID: 4ee37c58c652
Revises: 2d3b2fdff269
Create Date: 2014-11-17 20:49:11.927000

"""

# revision identifiers, used by Alembic.
revision = '4ee37c58c652'
down_revision = '2d3b2fdff269'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_change',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_change')
    ### end Alembic commands ###
