"""empty message

Revision ID: 4fe73b1cc4df
Revises: 5429cb33ab02
Create Date: 2014-11-06 17:00:37.299000

"""

# revision identifiers, used by Alembic.
revision = '4fe73b1cc4df'
down_revision = '5429cb33ab02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('limit_count', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('limit_of_participation', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('red_card_count', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('yellow_card_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'yellow_card_count')
    op.drop_column('player', 'red_card_count')
    op.drop_column('player', 'limit_of_participation')
    op.drop_column('player', 'limit_count')
    ### end Alembic commands ###
