"""empty message

Revision ID: 573e77e8d304
Revises: 1fa7d3248053
Create Date: 2014-11-13 14:25:30.299000

"""

# revision identifiers, used by Alembic.
revision = '573e77e8d304'
down_revision = '1fa7d3248053'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('match_count_tmp', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'match_count_tmp')
    ### end Alembic commands ###
