"""empty message

Revision ID: 59747d029dbf
Revises: 791eaef16ed
Create Date: 2014-11-10 15:32:53.284000

"""

# revision identifiers, used by Alembic.
revision = '59747d029dbf'
down_revision = '791eaef16ed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'red_card_count')
    op.drop_column('player', 'limit_count')
    op.drop_column('player', 'yellow_card_count')
    op.drop_column('player', 'limit_of_participation')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('limit_of_participation', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('yellow_card_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('limit_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('red_card_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
