"""empty message

Revision ID: 791eaef16ed
Revises: 17cc1910049c
Create Date: 2014-11-10 15:31:35.979000

"""

# revision identifiers, used by Alembic.
revision = '791eaef16ed'
down_revision = '17cc1910049c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
