"""empty message

Revision ID: ab5678099b0
Revises: 252a23273e32
Create Date: 2014-10-23 20:05:27.141000

"""

# revision identifiers, used by Alembic.
revision = 'ab5678099b0'
down_revision = '252a23273e32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
