"""empty message

Revision ID: fd1991cc204
Revises: 13109e7d6164
Create Date: 2014-11-04 15:19:02.189000

"""

# revision identifiers, used by Alembic.
revision = 'fd1991cc204'
down_revision = '13109e7d6164'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('key', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'key')
    ### end Alembic commands ###
